/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ServiceInterest = IDL.Variant({
  'laptops' : IDL.Null,
  'other' : IDL.Null,
  'cctv' : IDL.Null,
  'networking' : IDL.Null,
  'computers' : IDL.Null,
  'workstations' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : ServiceInterest,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'phoneNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiriesByServiceInterest' : IDL.Func(
      [ServiceInterest],
      [IDL.Vec(Inquiry)],
      ['query'],
    ),
  'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ServiceInterest, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ServiceInterest = IDL.Variant({
    'laptops' : IDL.Null,
    'other' : IDL.Null,
    'cctv' : IDL.Null,
    'networking' : IDL.Null,
    'computers' : IDL.Null,
    'workstations' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : ServiceInterest,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'phoneNumber' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiriesByServiceInterest' : IDL.Func(
        [ServiceInterest],
        [IDL.Vec(Inquiry)],
        ['query'],
      ),
    'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ServiceInterest, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };